### PR TITLE
Move 1 2

### PR DESCRIPTION
**Pull request by Jedelak**
tohle nedopadne, je tam bug

### CODE REVIEW

**Comment by mentor-tara** [comment]
Looks like something is wrong :astonished:	Please see the CI checks below for more information. Click the "Details" link for more information as shown in this screenshot.

Screenshot of CI checks[](error)

**Comment by Jedelak** [comment]
fix

**Comment by Jedelak** [comment]
odstraněn out

**Comment by Jedelak** [comment]
další PR

**Pull request closed without merging**
